---
- name:
  hosts: routers
  gather_facts: false


  tasks:
    - name:
      cisco.ios.ios_config:
        backup: true
        backup_options:
          filename: "{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M') }}.cfg"
          dir_path: "./backups"
